### ISSUE TITLE
Start Coding

### ISSUE THREAD

**Issue by niko998c** [RallerenP/nordic-motorhome-project#18]

**Comment by RallerenP** [comment]
We need a good baseline for our project.

- Spring Boot Initializr, Thymeleaf, Spring Boot Web

For hot-reload and rebuild, add 

```XML
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-devtools</artifactId>
</dependency>
```

to pom.xml

Go to `File \ Settings \ Build, Execution, Deployment` and tick `Build project automatically`.

Then hit `CTRL + A` open `Registry...` and set `compiler.automake.allow.when.app.running` to `true`.

---

When editing files we now no longer need to restart the entire program, just hit `CTRL + SHIFT + F9` and reload your page.
